/*******************************************************************************/
/*                                                                             */
/* LGEO Libray Include File                                                    */
/*                                                                             */
/* 20191011 Oliver Cordes                                                      */
/*                                                                             */
/* This file is in no way related to the LEGO(tm) Group.                       */
/* It is provided for private non-commercial use only.                         */
/*                                                                             */
/* lg_99301: Slope Brick 33  3 x  3 Double Concave                             */
/*                                                                             */
/*******************************************************************************/


#include "LDX.inc"


#declare LDX_99301_dot_dat =
union {
// Slope Brick 33  3 x  3 Double Concave
// Name: 99301.dat
// Author: Philippe Hurbain [Philo]
// !LDRAW_ORG Part UPDATE 2012-01
// !LICENSE Redistributable under CCAL version 2.0 : see CAreadme.txt
// BFC CERTIFY CCW
// !HISTORY 2012-03-30 [PTadmin] Official Update 2012-01
        object {
                LDX_stud4a_dot_dat_in_part
                matrix <1,0,0,0,-1,0,0,0,1,10,20,-30>
        }
// BFC INVERTNEXT
        object {
                LDX_2_dash_4cyli_dot_dat_in_part
                matrix <0,0,6,0,3,0,-6,0,0,10,4,-30>
        }
// BFC INVERTNEXT
        object {
                LDX_4_dash_4cyli_dot_dat_in_part
                matrix <0,0,6,0,-13,0,-6,0,0,10,20,-30>
        }
// BFC INVERTNEXT
        object {
                LDX_1_dash_4cyls_dot_dat_in_part
                matrix <6,0,0,0,-3,0,0,0,6,10,7,-30>
        }
// BFC INVERTNEXT
        object {
                LDX_1_dash_4cyls_dot_dat_in_part
                matrix <6,0,0,0,-3,0,0,0,-6,10,7,-30>
        }
        object {
                LDX_2_dash_4cyli_dot_dat_in_part
                matrix <0,0,8,0,4,0,-8,0,0,10,4,-30>
        }
        object {
                LDX_4_dash_4cyli_dot_dat_in_part
                matrix <0,0,8,0,-12,0,-8,0,0,10,20,-30>
        }
        object {
                LDX_1_dash_4cyls_dot_dat_in_part
                matrix <8,0,0,0,-4,0,0,0,8,10,8,-30>
        }
        object {
                LDX_1_dash_4cyls_dot_dat_in_part
                matrix <8,0,0,0,-4,0,0,0,-8,10,8,-30>
        }
        object {
                LDX_stud4a_dot_dat_in_part
                matrix <0,0,-1,0,-1,0,1,0,0,30,20,-10>
        }
// BFC INVERTNEXT
        object {
                LDX_2_dash_4cyli_dot_dat_in_part
                matrix <6,0,0,0,3,0,0,0,6,30,4,-10>
        }
// BFC INVERTNEXT
        object {
                LDX_4_dash_4cyli_dot_dat_in_part
                matrix <6,0,0,0,-13,0,0,0,6,30,20,-10>
        }
// BFC INVERTNEXT
        object {
                LDX_1_dash_4cyls_dot_dat_in_part
                matrix <0,0,-6,0,-3,0,6,0,0,30,7,-10>
        }
// BFC INVERTNEXT
        object {
                LDX_1_dash_4cyls_dot_dat_in_part
                matrix <0,0,-6,0,-3,0,-6,0,0,30,7,-10>
        }
        object {
                LDX_2_dash_4cyli_dot_dat_in_part
                matrix <8,0,0,0,4,0,0,0,8,30,4,-10>
        }
        object {
                LDX_4_dash_4cyli_dot_dat_in_part
                matrix <8,0,0,0,-12,0,0,0,8,30,20,-10>
        }
        object {
                LDX_1_dash_4cyls_dot_dat_in_part
                matrix <0,0,-8,0,-4,0,8,0,0,30,8,-10>
        }
        object {
                LDX_1_dash_4cyls_dot_dat_in_part
                matrix <0,0,-8,0,-4,0,-8,0,0,30,8,-10>
        }
        object {
                LDX_stud4a_dot_dat_in_part
                matrix <1,0,0,0,-1,0,0,0,1,30,20,-30>
        }
        object {
                LDX_2_dash_4cyls_dot_dat_in_part
                matrix <0,0,-8,0,-4,0,8,0,0,30,18,-30>
        }
        object {
                LDX_1_dash_4cyls2_dot_dat_in_part
                matrix <0,0,-8,0,-4,0,-8,0,0,30,14,-30>
        }
        object {
                LDX_1_dash_4cyls2_dot_dat_in_part
                matrix <8,0,0,0,-4,0,0,0,8,30,14,-30>
        }
        object {
                LDX_2_dash_4cyls_dot_dat_in_part
                matrix <8,0,0,0,-4,0,0,0,-8,30,18,-30>
        }
        object {
                LDX_4_dash_4cyli_dot_dat_in_part
                matrix <8,0,0,0,-2,0,0,0,8,30,20,-30>
        }
        object {
                LDX_1_dash_4cyli_dot_dat_in_part
                matrix <0,0,8,0,-4,0,-8,0,0,30,18,-30>
        }
// BFC INVERTNEXT
        object {
                LDX_2_dash_4cyls_dot_dat_in_part
                matrix <0,0,-6,0,-3,0,6,0,0,30,17,-30>
        }
// BFC INVERTNEXT
        object {
                LDX_1_dash_4cyls2_dot_dat_in_part
                matrix <0,0,-6,0,-3,0,-6,0,0,30,14,-30>
        }
// BFC INVERTNEXT
        object {
                LDX_1_dash_4cyls2_dot_dat_in_part
                matrix <6,0,0,0,-3,0,0,0,6,30,14,-30>
        }
// BFC INVERTNEXT
        object {
                LDX_2_dash_4cyls_dot_dat_in_part
                matrix <6,0,0,0,-3,0,0,0,-6,30,17,-30>
        }
// BFC INVERTNEXT
        object {
                LDX_4_dash_4cyli_dot_dat_in_part
                matrix <6,0,0,0,-3,0,0,0,6,30,20,-30>
        }
// BFC INVERTNEXT
        object {
                LDX_1_dash_4cyli_dot_dat_in_part
                matrix <0,0,6,0,-3,0,-6,0,0,30,17,-30>
        }
        object {
                LDX_stud4a_dot_dat_in_part
                matrix <1,0,0,0,-1,0,0,0,1,10,20,-10>
        }
// BFC INVERTNEXT
        object {
                LDX_3_dash_4cyli_dot_dat_in_part
                matrix <6,0,0,0,3,0,0,0,6,10,4,-10>
        }
        object {
                LDX_3_dash_4cyli_dot_dat_in_part
                matrix <8,0,0,0,4,0,0,0,8,10,4,-10>
        }
        object {
                LDX_1_dash_4cyls_dot_dat_in_part
                matrix <0,0,-7.99999,0,-4,0,7.99999,0,0,10,8,-10>
        }
        object {
                LDX_1_dash_4cyls_dot_dat_in_part
                matrix <8,0,0,0,-4,0,0,0,-8,10,8,-10>
        }
        object {
                LDX_4_dash_4cyli_dot_dat_in_part
                matrix <8,0,0,0,12,0,0,0,8,10,8,-10>
        }
// BFC INVERTNEXT
        object {
                LDX_1_dash_4cyls_dot_dat_in_part
                matrix <0,0,-6,0,-3,0,6,0,0,10,7,-10>
        }
// BFC INVERTNEXT
        object {
                LDX_1_dash_4cyls_dot_dat_in_part
                matrix <6,0,0,0,-3,0,0,0,-6,10,7,-10>
        }
// BFC INVERTNEXT
        object {
                LDX_4_dash_4cyli_dot_dat_in_part
                matrix <6,0,0,0,13,0,0,0,6,10,7,-10>
        }
        object {
                LDX_stug_dash_1x3_dot_dat_in_part
                matrix <1,0,0,0,1,0,0,0,1,20,0,0>
        }
        object {
                LDX_stug_dash_2x1_dot_dat_in_part
                matrix <1,0,0,0,1,0,0,0,1,0,0,-30>
        }
// BFC INVERTNEXT
        mesh2 {
                vertex_vectors {
                        25,
                        <-10,0,-50>, <-10,0,10>, <-10,24,-50>, <-10,24,10>,
                        <-6,4,-46>, <-6,4,6>, <-6,24,-46>, <-6,24,6>,
                        <10,0,-50>, <10,0,-10>, <10,4,-46>, <10,4,-10>,
                        <42,20,-46>, <42,20,-42>, <46,4,-10>, <46,4,6>,
                        <46,20,-46>, <46,20,-42>, <46,24,-46>, <46,24,6>,
                        <50,0,-10>, <50,0,10>, <50,20,-50>, <50,24,-50>,
                        <50,24,10>
                }
                normal_vectors {
                        10,
                        <-1,0,0>, <-0.447214,0.894427,0>, <0,-1,0>, <0,-0.894427,-0.447214>,
                        <0,0,-1>, <0,0,1>, <0,0.894427,0.447214>, <0,1,0>,
                        <0.447214,-0.894427,0>, <1,0,0>
                }
                face_indices {
                        46,
                        <24, 19, 7>, <24, 7, 3>, <3, 7, 6>, <3, 6, 2>,
                        <2, 6, 18>, <2, 18, 23>, <23, 18, 19>, <23, 19, 24>,
                        <16, 12, 13>, <16, 13, 17>, <1, 9, 20>, <1, 20, 21>,
                        <0, 8, 9>, <0, 9, 1>, <15, 14, 11>, <15, 11, 5>,
                        <5, 11, 10>, <5, 10, 4>, <16, 17, 19>, <16, 19, 18>,
                        <15, 19, 17>, <15, 17, 14>, <6, 12, 16>, <6, 16, 18>,
                        <4, 10, 12>, <4, 12, 6>, <24, 21, 22>, <24, 22, 23>,
                        <22, 0, 2>, <22, 2, 23>, <0, 22, 8>, <20, 22, 21>,
                        <8, 22, 9>, <9, 22, 20>, <10, 11, 13>, <10, 13, 12>,
                        <13, 11, 14>, <13, 14, 17>, <3, 24, 21>, <3, 21, 1>,
                        <3, 1, 0>, <3, 0, 2>, <7, 19, 15>, <7, 15, 5>,
                        <7, 5, 4>, <7, 4, 6>
                }
                normal_indices {
                        46,
                        <2, 2, 2>, <2, 2, 2>, <2, 2, 2>, <2, 2, 2>,
                        <2, 2, 2>, <2, 2, 2>, <2, 2, 2>, <2, 2, 2>,
                        <2, 2, 2>, <2, 2, 2>, <7, 7, 7>, <7, 7, 7>,
                        <7, 7, 7>, <7, 7, 7>, <2, 2, 2>, <2, 2, 2>,
                        <2, 2, 2>, <2, 2, 2>, <9, 9, 9>, <9, 9, 9>,
                        <9, 9, 9>, <9, 9, 9>, <4, 4, 4>, <4, 4, 4>,
                        <4, 4, 4>, <4, 4, 4>, <0, 0, 0>, <0, 0, 0>,
                        <5, 5, 5>, <5, 5, 5>, <5, 5, 5>, <0, 0, 0>,
                        <1, 1, 1>, <6, 6, 6>, <8, 8, 8>, <8, 8, 8>,
                        <3, 3, 3>, <3, 3, 3>, <5, 5, 5>, <5, 5, 5>,
                        <0, 0, 0>, <0, 0, 0>, <5, 5, 5>, <5, 5, 5>,
                        <0, 0, 0>, <0, 0, 0>
                }
        }
}


#declare lg_99301 = object{
          LDX_99301_dot_dat
          LDXSeamMatrix(60, 28, 60, 20, 10, -20)
          scale 1/25.
          rotate x*-90
          //rotate y*180
          rotate z*-90
}
