/*******************************************************************************/
/*                                                                             */
/* LGEO Libray Include File                                                    */
/*                                                                             */
/* 20200209 Oliver Cordes                                                      */
/*                                                                             */
/* This file is in no way related to the LEGO(tm) Group.                       */
/* It is provided for private non-commercial use only.                         */
/*                                                                             */
/* lg_XXXX: */
/*                                                                             */
/*******************************************************************************/


#include "LDX.inc"


#declare lg = object{
          scale 1/25.
          rotate x*-90
          //rotate y*180
          rotate z*-90
}
