"""

pyldd/lego_defs.py

Author: Oliver Cordes

History:
 2018-12-12:
   - add all LEGO/LGEO defs
"""

import numpy as np

LG_KNOB_RADIUS = 0.24
LG_KNOB_HEIGHT = 0.16
LG_KNOB_HEIGHT_LOGO = 0.16
LG_KNOB_INNER_RADIUS = 0.16
LG_WALL_WIDTH = 0.16
LG_BRICK_WIDTH = 0.8
LG_BRICK_HEIGHT = 0.96
LG_BRICK_INNER_HEIGHT = 0.84
LG_PLATE_HEIGHT = 0.32
LG_PLATE_INNER_HEIGHT = 0.2
LG_TOP_HEIGHT = LG_BRICK_HEIGHT-LG_BRICK_INNER_HEIGHT
LG_CYLINDER_RADIUS = (np.sqrt(2)*LG_BRICK_WIDTH/2-LG_KNOB_RADIUS)
LG_CYLINDER_WALL_WIDTH = (LG_CYLINDER_RADIUS-LG_KNOB_RADIUS)
LG_CORNER_SPACE = 0.016
LG_KNOB_CORNER_SPACE = LG_CORNER_SPACE * 1.5
LG_CROSSAXLE_WIDTH = 0.18
LG_GRID_WIDTH=LG_BRICK_WIDTH/np.sqrt(2)-2*LG_KNOB_RADIUS
LG_E = 0.01
LG_EE = 0.0000001
